# Site settings
title: Antitypical
email: rob.rix@me.com
description: > # this means to ignore newlines until "baseurl:"
  Words by Rob Rix.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://antitypical.com" # the base hostname & protocol for your site
twitter_username: rob_rix
github_username:  robrix

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
